# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: S:/Downloads/Testing/Real_Time_Video_Filter/Real_Time_Video_Filter.srcs/sources_1/bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_axi_vdma_0_0/Real_Time_Video_Filter_axi_vdma_0_0.xci
# IP: The module: 'Real_Time_Video_Filter_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/Downloads/Testing/Real_Time_Video_Filter/Real_Time_Video_Filter.gen/sources_1/bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_axi_vdma_0_0/Real_Time_Video_Filter_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Real_Time_Video_Filter_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: s:/Downloads/Testing/Real_Time_Video_Filter/Real_Time_Video_Filter.gen/sources_1/bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_axi_vdma_0_0/Real_Time_Video_Filter_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Real_Time_Video_Filter_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: s:/Downloads/Testing/Real_Time_Video_Filter/Real_Time_Video_Filter.gen/sources_1/bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_axi_vdma_0_0/Real_Time_Video_Filter_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Real_Time_Video_Filter_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: S:/Downloads/Testing/Real_Time_Video_Filter/Real_Time_Video_Filter.srcs/sources_1/bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_axi_vdma_0_0/Real_Time_Video_Filter_axi_vdma_0_0.xci
# IP: The module: 'Real_Time_Video_Filter_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/Downloads/Testing/Real_Time_Video_Filter/Real_Time_Video_Filter.gen/sources_1/bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_axi_vdma_0_0/Real_Time_Video_Filter_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Real_Time_Video_Filter_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: s:/Downloads/Testing/Real_Time_Video_Filter/Real_Time_Video_Filter.gen/sources_1/bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_axi_vdma_0_0/Real_Time_Video_Filter_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Real_Time_Video_Filter_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: s:/Downloads/Testing/Real_Time_Video_Filter/Real_Time_Video_Filter.gen/sources_1/bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_axi_vdma_0_0/Real_Time_Video_Filter_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Real_Time_Video_Filter_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
