# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedboard.xdc

# Block Designs: bd/Real_Time_Video_Filter/Real_Time_Video_Filter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter || ORIG_REF_NAME==Real_Time_Video_Filter} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_processing_system7_0_0/Real_Time_Video_Filter_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_processing_system7_0_0 || ORIG_REF_NAME==Real_Time_Video_Filter_processing_system7_0_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_RGB_to_RGBX_0_0/Real_Time_Video_Filter_RGB_to_RGBX_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_RGB_to_RGBX_0_0 || ORIG_REF_NAME==Real_Time_Video_Filter_RGB_to_RGBX_0_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_RGBX_AXI_Stream_0_0/Real_Time_Video_Filter_RGBX_AXI_Stream_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_RGBX_AXI_Stream_0_0 || ORIG_REF_NAME==Real_Time_Video_Filter_RGBX_AXI_Stream_0_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_ov7670_controller_0_0/Real_Time_Video_Filter_ov7670_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_ov7670_controller_0_0 || ORIG_REF_NAME==Real_Time_Video_Filter_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_ov7670_capture_0_0/Real_Time_Video_Filter_ov7670_capture_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_ov7670_capture_0_0 || ORIG_REF_NAME==Real_Time_Video_Filter_ov7670_capture_0_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_axi_vdma_0_0/Real_Time_Video_Filter_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_axi_vdma_0_0 || ORIG_REF_NAME==Real_Time_Video_Filter_axi_vdma_0_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_vga_controller_0_0/Real_Time_Video_Filter_vga_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_vga_controller_0_0 || ORIG_REF_NAME==Real_Time_Video_Filter_vga_controller_0_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_clk_wiz_0_0/Real_Time_Video_Filter_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_clk_wiz_0_0 || ORIG_REF_NAME==Real_Time_Video_Filter_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_ps7_0_axi_periph_0/Real_Time_Video_Filter_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_ps7_0_axi_periph_0 || ORIG_REF_NAME==Real_Time_Video_Filter_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_rst_ps7_0_100M_0/Real_Time_Video_Filter_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_rst_ps7_0_100M_0 || ORIG_REF_NAME==Real_Time_Video_Filter_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_axi_mem_intercon_0/Real_Time_Video_Filter_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_axi_mem_intercon_0 || ORIG_REF_NAME==Real_Time_Video_Filter_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_rst_ps7_0_100M_1_0/Real_Time_Video_Filter_rst_ps7_0_100M_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_rst_ps7_0_100M_1_0 || ORIG_REF_NAME==Real_Time_Video_Filter_rst_ps7_0_100M_1_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_xbar_0/Real_Time_Video_Filter_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_xbar_0 || ORIG_REF_NAME==Real_Time_Video_Filter_xbar_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_axi_gpio_0_0/Real_Time_Video_Filter_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_axi_gpio_0_0 || ORIG_REF_NAME==Real_Time_Video_Filter_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_auto_pc_0/Real_Time_Video_Filter_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_auto_pc_0 || ORIG_REF_NAME==Real_Time_Video_Filter_auto_pc_0} -quiet] -quiet

# IP: bd/Real_Time_Video_Filter/ip/Real_Time_Video_Filter_auto_pc_1/Real_Time_Video_Filter_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Real_Time_Video_Filter_auto_pc_1 || ORIG_REF_NAME==Real_Time_Video_Filter_auto_pc_1} -quiet] -quiet

# XDC: s:/Documents/GitHub/Real_Time_Video_Filter/Real_Time_Video_Filter.gen/sources_1/bd/Real_Time_Video_Filter/Real_Time_Video_Filter_ooc.xdc
